---
title: "Student performance in exam"
author: "Donggyu Isaac Hills"
date: '2021 3 1 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
exam <- read.csv(file = "StudentsPerformance.csv")
```

# Set up 
```{r set up}
# Checking if there is any missing values, which returns none
which(is.na(exam), arr.ind=TRUE)
# Renaming columns
colnames(exam)<-gsub("\\.","\\_",colnames(exam))
# Shows changes
head(exam, 3)
# Summary of data
summary(exam)
```

# Does gender affect performance?
```{r gender}
plot_gender <- ggplot(data = exam, 
                      aes(x = gender,
                          fill = gender)) + 
               geom_bar(stat = "count") +
               xlab("Gender") + 
               ylab("Count") +
               ggtitle("Male Female Ratio")
plot_gender

# Comparing math score by gender  
gender_math_graph <- exam %>% select(gender, `math_score`) %>% filter(!is.na(math_score)) %>% ggplot(aes(x=gender, y = math_score, color = gender)) + geom_boxplot() + geom_jitter(width = 0.2, alpha = 0.2)


# Comparing reading score by gender 
gender_reading_graph <- exam %>% select(gender, `reading_score`) %>% filter(!is.na(reading_score)) %>% ggplot(aes(x=gender, y = reading_score, color = gender)) + geom_boxplot() + geom_jitter(width = 0.2, alpha = 0.2)


#Comparing writing score by gender 
gender_writing_graph <- exam %>% select(gender, `writing_score`) %>% filter(!is.na(writing_score)) %>% ggplot(aes(x=gender, y = writing_score, color = gender)) + geom_boxplot() + geom_jitter(width = 0.2, alpha = 0.2)
```

```{r gender graph , echo=FALSE}
## Does race affect performance?
gender_math_graph
gender_reading_graph
gender_writing_graph
```

```{r Race}
math_race = ggplot(data = exam) + 
  geom_boxplot(mapping = aes(x = race_ethnicity, y = math_score, fill = race_ethnicity)) +
  labs(x = "Race/Ethnicity", y = "Math Scores")


reading_race = ggplot(data = exam) + 
  geom_boxplot(mapping = aes(x = race_ethnicity, y = reading_score, fill = race_ethnicity)) +
  labs(x = "Race/Ethnicity", y = "Reading Scores")
  

writing_race = ggplot(data = exam) +
  geom_boxplot(mapping = aes(x = race_ethnicity, y = writing_score, fill = race_ethnicity)) +
  labs(x = "Race/Ethnicity", y = "Writing Scores")
```

```{r Race graph, echo=FALSE}
math_race
reading_race
writing_race
```

