---
title: "grocery"
author: "Donggyu Isaac Hills"
date: '2021 3 16 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
grocery <- read.csv("Groceries_dataset.csv")
```

#### Before clean up  
```{r Before Clean up, echo=FALSE}
kable(head(grocery))
```

```{r set up}
# Checking NA values
sum(is.na(grocery))
# Rename and re-class the columns
names(grocery) <- c("member_id", "date", "item")
grocery$member_id <- as_factor(grocery$member_id)
grocery$date <- as_date(dmy(grocery$date))
grocery$item <- as_factor(grocery$item)
# Create new columns with number of dates since #epoch date(January 1, 1970).
grocery$trans_id <- as_factor(paste0(grocery$member_id, unclass(grocery$date)))
grocery$month <- month(grocery$date)
grocery$weekday <- weekdays(grocery$date)

item_list <- unique(grocery$item)
num_items <- length(list)
member_list <- unique(grocery$member_id)
num_members <- length(member_list)

# Showing number of transactions. 
num_trans <- length(unique(grocery$trans_id))
paste0("From 2014 to 2015, there were ",num_trans, " transactions.")
```


#### After clean up 
```{r After clean up, echo=FALSE}
kable(head(grocery))
```

<br> Here is the list of items purchased. <br> 
```{r item list, echo=FALSE}
item_list
```

```{r Count and prep visualization for top ten }
count <- count(grocerycery, grocery$item)
names(count) <- c("item", "num")

# sort items by number of times purchased
sorted_count <- count[order(-count$num),]

# Add a field that converts count to fraction of total purchases
sorted_count$portion <- sorted_count$num/num_trans

top_ten <- sorted_count[1:10,]
# Reverse the order for horizontal Pareto chart
top_ten_rev<- sorted_count[10:1,]

#graph for top ten
top_ten$item <- factor(top_ten$item, levels = top_ten_rev$item)
top_ten_graph <- ggplot(data = top_ten, aes(x = item, y = portion)) +
                   geom_bar(stat = "identity", fill = "steelblue") +
                   labs(title = "Top 10 items", y = "Fraction of transaction") +
                   coord_flip()

```

```{r Show top ten, echo=FALSE}
top_ten
top_ten_graph
```

#### Transaction made by day
```{r By day}
# Presents shopping trips by  transaction id
day <- unique(data.frame(weekday = grocery$weekday, trans_id = grocery$trans_id))

# Puts days in order 
day$weekday <- factor(day$weekday, levels = c('Sunday', 'Monday', 'Tuesday',
                               'Wednesday', 'Thursday', 'Friday', 'Saturday'))
# Arrange shopping trips by days of the week count them by day
daily_trans <- day %>%
  groceryup_by(weekday) %>%
  dplyr::summarize(n = n())
  
per_day <- ggplot(data = day, aes(x = weekday), ) +
  geom_bar(fill = "steelblue")
```

```{r Per day visualization, echo=FALSE}
per_day
```

<br> Zooming in due to unclear difference <br>
```{r Zoomed per day visualization, echo=FALSE}
ggplot(data = day, aes(x = weekday)) + 
    geom_bar(fill = "steelblue") + 
    coord_cartesian(ylim = c(2000,2200))
```

```{r By Month}
milk <- grocery[grocery$item == "whole milk",-c(1,2,3,6)]
other_veg <- grocery[grocery$item == "other vegetables",-c(1,2,3,6)]
root_veg <- grocery[grocery$item == "root vegetables",-c(1,2,3,6)]
rolls <- grocery[grocery$item == "rolls/buns",-c(1,2,3,6)]
soda <- grocery[grocery$item == "soda",-c(1,2,3,6)]
yogurt <- grocery[grocery$item == "yogurt",-c(1,2,3,6)]
tropic_fruit <- grocery[grocery$item == "tropical fruit",-c(1,2,3,6)]
citrus_fruit <- grocery[grocery$item == "citrus fruit",-c(1,2,3,6)]
water <- grocery[grocery$item == "bottled water",-c(1,2,3,6)]
sausage <- grocery[grocery$item == "sausage",-c(1,2,3,6)]

# Combine two years of data and groceryup by month of the year
by_month <- function(x) {
    x %>%
        groceryup_by(month) %>%
        dplyr::summarize(num = n())
}

month_milk <- by_month(milk)
month_other_veg <- by_month(other_veg)
month_root_veg <- by_month(root_veg)
month_rolls <- by_month(rolls)
month_soda <- by_month(soda)
month_yogurt <- by_month(yogurt)
month_tropic_fruit <- by_month(tropic_fruit)
month_citrus_fruit <- by_month(citrus_fruit)
month_water <- by_month(water)
month_sausage <- by_month(sausage)

month_table <- data.frame(month = as.numeric(c(1:12)),
                                           milk = month_milk$num,
                                           other_veg = month_other_veg$num,
                                           root_veg = month_root_veg$num,
                                           rolls = month_rolls$num,
                                           soda = month_soda$num,
                                           yogurt = month_yogurt$num,
                                           tropic_fruit = month_tropic_fruit$num,
                                           citrus_fruit =month_citrus_fruit$num,
                                           water = month_water$num,
                                           sausage = month_sausage$num)


```

```{r by month vis, echo=FALSE}
kable(month_table)
```

```{r top six}
# Plotting top six
top_six <- ggplot(data = month_table, aes(x = month)) +
    geom_line(aes(y = milk, color = "red")) +    
    geom_line(aes(y = other_veg, color = "green")) + 
    geom_line(aes(y = rolls, color = "black")) +
    geom_line(aes(y = soda, color = "blue")) +
    geom_line(aes(y = yogurt, color = "purple")) +
    scale_x_continuous("month", 
                       breaks = c(1:12), 
                       labels = month.abb) +
    ylab("Number of Transactions") +

    scale_color_identity(name = "Product",
                         breaks = c("red", "green", "black", "blue", "purple"),
                         labels = c("Milk", "Other Vegetables", "Rolls/Buns", "Soda", "yogurt"),
                         guide = "legend")
```

```{r top six vis, echo=FALSE}
top_six
```