---
title: "Loan"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

# Data cleaning
Checking and erasing missing data. 

```{r Cleaning}
# Dataset of 614 loan ID
loan <- read.csv(file = "loanapproval.csv") 

#Indicates rows and columns of missing data
which(is.na(loan), arr.ind=TRUE)

#Removes rows with missing data. 
loan <- na.omit(loan)

#Showing cleaned dataset of 529 loan Id. 
head(loan, )


```

# Visualization 
```{r  visualization I}

#Presents relationship between applicant's income and amount of loan in a scatter plot
ggplot(data = loan) + 
  geom_point(mapping = aes(x = LoanAmount, y = ApplicantIncome ))

#Correlation is unclear due to outliers

#Removes outlier of loan amount and applicant's income
loan_xoutlier <- loan

boxplot(loan$LoanAmount, plot=FALSE)$out
loan_Amount_outliers <- boxplot(loan$LoanAmount, plot=FALSE)$out
loan_xoutlier <- loan_xoutlier[-which(loan_xoutlier$LoanAmount %in% loan_Amount_outliers),]

boxplot(loan$ApplicantIncome, plot=FALSE)$out
income_outliers <- boxplot(loan$ApplicantIncome, plot=FALSE)$out
loan_xoutlier <- loan_xoutlier[-which(loan_xoutlier$ApplicantIncome %in% income_outliers),]


#Presents relationship between applicant's income and amount of loan in a scatter plot without outliers. 469 loan IDs. The graph indicates a positive correlation. 
ggplot(data = loan_xoutlier) + 
  geom_point(mapping = aes(x = LoanAmount, y = ApplicantIncome ))



```


```{r Visualization II}
#Add income of applicants and coapplicants
loan_xoutlier$combine_income <- loan_xoutlier[,7] + loan_xoutlier[,8]

as.integer(loan_xoutlier$combine_income)

#Presents relationship betweeen combined income and amount of loan without removing outliers 
ggplot(data = loan_xoutlier) + 
  geom_point(mapping = aes(x = LoanAmount, y = combine_income ))

#Removing outlier in combined income
boxplot(loan_xoutlier$combine_income, plot=FALSE)$out
combine_income_outliers <- boxplot(loan_xoutlier$combine_income, plot=FALSE)$out
loan_xoutlier <- loan_xoutlier[-which(loan_xoutlier$combine_income %in% combine_income_outliers),]

#New scatter plot without outliers 
ggplot(data = loan_xoutlier) + 
  geom_point(mapping = aes(x = LoanAmount, y = combine_income ))


``` 

```{r Visualization III}

#Presenting ratio of approved and disapproved loan status by dividing combined income over loan amount requested. 
loan_xoutlier$Income_Loan_Ratio <-  (loan_xoutlier[,9] * 1000) / loan_xoutlier[,14] 

ggplot(loan_xoutlier, 
       aes(x = Loan_Status, 
           y = Income_Loan_Ratio)) +
  geom_boxplot() +
  labs(title = "Loan / Income Ratio ")

boxplot(loan_xoutlier$Income_Loan_Ratio , plot=FALSE)$out
Income_Loan_Ratio_outliers <- boxplot(loan_xoutlier$Income_Loan_Ratio, plot=FALSE)$out
loan_xoutlier <- loan_xoutlier[-which(loan_xoutlier$Income_Loan_Ratio %in% Income_Loan_Ratio_outliers),]


ggplot(loan_xoutlier, 
       aes(x = Loan_Status, 
           y = Income_Loan_Ratio)) +
  geom_boxplot() +
  labs(title = "Loan / Income Ratio")

```

